<a href="https://colab.research.google.com/github/GiteshWagh/Experiment_No_8/blob/main/Experiment_No_8___NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Experiment 8 : Tools For Exploratory Data Analysis - NumPy

# Name - Gitesh Wagh
# PRN - 25070123163
# Branch - F.Y. E&TC (2025-29)
# Batch - A1
# Subject - Exploratory Data Analysis With Python

In [ ]:
# NumPy - Numerical Python

In [28]:
# Study Of Basics Of NumPy
import numpy as np # Importing the NumPy
Array1 = np.array([[1,2,3],[4,5,6]])
print(Array1)

Dimension = Array1.ndim # Gives the dimensions of array
print(Dimension)

Shape = Array1.shape # Gives (Rows, Columns)
print(Shape)

Size = Array1.size # Gives the Total number of elements
print(Size)

Type = Array1.dtype # Gives the datatype of elements
print(Type)

Null_Matrix = np.zeros((2,3))
print(Null_Matrix)

Ones_Matrix = np.ones((2,3)) # Gives the unit matrix with specific order
print(Ones_Matrix)

Diagonal_Matrix = np.eye((7)) # Gives the diagonal matrix with specific order
print(Diagonal_Matrix)

print(np.arange(1,10,2))

print(np.linspace(1,10,5))

print(Array1+2) # Each element of the array is Added by 2

Mean = np.mean(Array1) # Mean of the data in array
print(Mean)

Median = np.median(Array1) # Median of array data
print(Median)

MinValue = np.min(Array1) # Minimum value in data
print(MinValue)

MaxValue = np.max(Array1) # Maximum value in data
print(MaxValue)

Sum = np.sum(Array1)
print("Sum of the data in array is : ",Sum)


[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]
[[3 4 5]
 [6 7 8]]
3.5
3.5
1
6
Sum of the data in array is :  21
